version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      UNIFI_IP: '192.168.1.1'
      UNIFI_PORT: 443
      UNIFI_USERNAME: 'admin'
      UNIFI_PASSWORD: 'password'
      UNIFI_SITE_ID: 'default'
      AUTH_PASSWORD: '0000'
      AUTH_TOKEN: '00000000-0000-0000-0000-000000000000'
      AUTH_DISABLE: 'false'
      VOUCHER_TYPES: '480,1,,,;'
      VOUCHER_CUSTOM: 'true'
      SERVICE_WEB: 'true'
      SERVICE_API: 'false'
      SMTP_FROM: ''
      SMTP_HOST: ''
      SMTP_PORT: ''
      SMTP_SECURE: ''
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
      LOG_LEVEL: 'info'
