version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      UNIFI_IP: '192.168.1.1'
      UNIFI_PORT: 443
      UNIFI_USERNAME: 'admin'
      UNIFI_PASSWORD: 'password'
      UNIFI_SITE_ID: 'default'
      SECURITY_CODE: '0000'
      DISABLE_AUTH: 'false'
      VOUCHER_TYPES: '480,0,,,;'
      SERVICE_WEB: 'true'
      SERVICE_API: 'false'
